---
name: 'Run NiFi Registry in OIDC mode with DB storage and execute autotests'
description: 'Runs NiFi Registry and other containers and executes autotests'
inputs:
  results-dir:
    description: 'Directory to store results'
    required: false
    default: 'oidc'
runs:
  using: "composite"
  steps:
    - name: Prepare env
      shell: bash
      run: |
        echo "Preparing env..."
        chmod +x .github/workflows/sh/*.sh
        . .github/workflows/sh/nifi-lib.sh
        prepare_results_dir "${{ inputs.results-dir }}"
        generate_tls_passwords
        create_docker_env_file
        mkdir -p ./temp-vol/pg-db/
        mkdir -p ./temp-vol/tls-cert/
        mkdir -p ./temp-vol/tls-cert/nifi-registry/
        chmod -R 777 ./temp-vol
    - name: Run local nifi
      shell: bash
      run: |
        echo "Starting containers..."
        docker compose -f .github/docker/oidc/docker-compose.yaml --env-file ./docker.env up -d
    - name: Wait for nifi-registry container to start
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        NIFI_CLIENT_PASSWORD=$(cat ./temp-vol/tls-cert/nifi/CN=admin_OU=NIFI.password)
        wait_nifi_reg_container "localhost" "18080" ".github/docker/oidc/docker-compose.yaml" "true" \
          "5" "40" "${{ inputs.results-dir }}" "./temp-vol/tls-cert/nifi/nifi-cert.pem" \
          "./temp-vol/tls-cert/nifi/CN=admin_OU=NIFI.p12" "$NIFI_CLIENT_PASSWORD"
    - name: Run nifi registry policy API tests
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'NiFi_Registry_Policy_API_Tests.postman_collection.json'
        env-name: 'NiFi_Reg_AT_TLS.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'main-tests'
        tls-certs-dir: "./temp-vol/tls-cert"
        tls-ca-certs: "nifi/nifi-cert.pem"
        tls-client-certs-config: "newman-tls-config.json"
    - name: Run nifi registry main API tests
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'NiFi_Registry_API_Tests.postman_collection.json'
        env-name: 'NiFi_Reg_AT_TLS.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'main-tests'
        tls-certs-dir: "./temp-vol/tls-cert"
        tls-ca-certs: "nifi/nifi-cert.pem"
        tls-client-certs-config: "newman-tls-config.json"
    - name: Cleanup after tests
      shell: bash
      continue-on-error: true
      run: |
        echo "Stopping and removing containers"
        docker compose -f .github/docker/oidc/docker-compose.yaml --env-file ./docker.env down -v
        echo "Removing temporary volume data"
        sudo rm -rf ./temp-vol/