---
services:
  nifi-registry:
    image: ghcr.io/netcracker/nifi-registry:latest
    volumes:
      - nifi-reg-db:/opt/nifi-registry/nifi-registry-current/database
      - nifi-reg-flow:/opt/nifi-registry/nifi-registry-current/flow_storage
    ports:
      - 127.0.0.1:18080:18080
    environment:
      - AUTH=none
volumes:
  nifi-reg-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/nifi-reg/database/
  nifi-reg-flow:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/nifi-reg/flow-storage/