# Application Configuration
cloud.microservice.namespace=${NAMESPACE:local}
cloud.microservice.name=${MICROSERVICE_NAME:qubership-nifi-registry}
quarkus.application.name=${MICROSERVICE_NAME:qubership-nifi-registry}

# Consul Configuration
quarkus.consul-source-config.enabled=${CONSUL_ENABLED:true}
quarkus.consul-source-config.agent.url=${CONSUL_URL:http://localhost:8500}
quarkus.consul-source-config.properties-root=config/${cloud.microservice.namespace}/application,config/${cloud.microservice.namespace}/${cloud.microservice.name}
#TODO - add logic for M2M here:
quarkus.consul-source-config.m2m.enabled=false

# NiFi Registry Configuration Paths
nifi.registry.config.path=${NIFI_REGISTRY_HOME:/opt/nifi-registry}/conf/
nifi.registry.notification.path=/tmp/

# Application Settings
quarkus.banner.enabled=false

# Logging Configuration
quarkus.log.level=${ROOT_LOG_LEVEL:INFO}
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n

# Disable live reload and dev mode features for production
quarkus.live-reload.instrumentation=false
