---
services:
  nifi-registry:
    image: local-nifi-registry:test
    ports:
      - 127.0.0.1:18080:18080
    environment:
      - AUTH=none
    container_name: local-nifi-registry-plain
    hostname: nifi-registry
  consul:
    image: hashicorp/consul:1.20
    ports:
      - 127.0.0.1:8500:8500
    hostname: consul