---
name: docker-build-and-test

on:
  push:
    paths:
      - '.github/workflows/docker-build-and-test.yml'
      - 'nifi-registry-db-util/**'
      - 'nifi-registry-migration-util/**'
      - 'nifi-registry-util/**'
      - 'qubership-cached-providers/**'
      - 'qubership-nifi-registry-consul/**'
      - 'pom.xml'
      - 'Dockerfile'
      - 'conf-template-custom/**'
      - 'nifi-scripts/**'
      - '.github/actions/**'
      - '.github/collections/**'
      - '.github/docker/**'
      - '.github/configuration/**'
      - '.github/workflows/sh/**'
  pull_request:
    paths:
      - '.github/workflows/docker-build-and-test.yml'
      - 'nifi-registry-db-util/**'
      - 'nifi-registry-migration-util/**'
      - 'nifi-registry-util/**'
      - 'qubership-cached-providers/**'
      - 'qubership-nifi-registry-consul/**'
      - 'pom.xml'
      - 'Dockerfile'
      - 'conf-template-custom/**'
      - 'nifi-scripts/**'
      - '.github/actions/**'
      - '.github/collections/**'
      - '.github/docker/**'
      - '.github/configuration/**'
      - '.github/workflows/sh/**'
  workflow_dispatch:
    inputs:
      java-version:
        required: false
        type: string
        default: "21"
        description: 'Java version (e.g., 21)'
permissions:
  contents: read
jobs:
  mvn:
    uses: ./.github/workflows/maven-build-and-test.yml
    with:
      java-version: ${{ github.event.inputs.java-version || '21' }}
      artifact-id: 'qubership-nifi-registry-local-build'
      upload-artifact: true
      skip-sonar: true
  docker-build-and-test:
    strategy:
      fail-fast: false
      matrix:
        run-mode: [ 'plain', 'tls', 'tls-db', 'tls-db-std', 'oidc', 'upgrade-plain', 'upgrade-tls-db', 'upgrade-tls-db-std' ]
    needs: [ mvn ]
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        shell: bash
        run: |
          mkdir -p ./test-results/
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          persist-credentials: false
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: 'qubership-nifi-registry-local-build'
      - name: Run local docker build
        run: docker build -t local-nifi-registry:test .
      - name: Run upgrade tests with mode = ${{ matrix.run-mode }}
        if: ${{ startsWith(matrix.run-mode, 'upgrade-') }}
        uses: ./.github/actions/run-nifi-reg-upgrade-tests
        with:
          run-mode: '${{ matrix.run-mode }}'
      - name: Run tests with mode = ${{ matrix.run-mode }}
        if: "${{ !startsWith(matrix.run-mode, 'upgrade-') }}"
        uses: ./.github/actions/run-nifi-reg-tests-generic
        with:
          run-mode: '${{ matrix.run-mode }}'
      - name: Verify test results
        shell: bash
        run: |
          echo "Preparing summary..."
          {
            echo "## Autotests summary"
            echo "Run mode = ${{ matrix.run-mode }}"
            echo ""
            echo "| Step                                           | Result                     |"
            echo "| ---------------------------------------------- | -------------------------- |"
            cat ./test-results/*/summary_*.txt
            echo ""
          } >> $GITHUB_STEP_SUMMARY
          echo "Checking test results for failures..."
          failed_cnt=$(find ./test-results -name "failed_*.lst" | wc -l)
          echo "Found failed steps = $failed_cnt"
          if [ "$failed_cnt" == "0" ]; then
            echo "All tests were successful!"
            echo "All tests were successful!" >> $GITHUB_STEP_SUMMARY
          else
            echo "Some tests ($failed_cnt) failed. Marking as failure."
            echo "Some tests ($failed_cnt) failed. Marking as failure." >> $GITHUB_STEP_SUMMARY
            if [ -f ./docker.env ]; then
              if [ -d "./test-results/${{ matrix.run-mode }}" ]; then
                echo "Copying docker.env to test-results/${{ matrix.run-mode }}..."
                cp ./docker.env "./test-results/${{ matrix.run-mode }}/"
              fi
            fi
            exit 1;
          fi
      - name: Upload test results
        if: failure() || cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: nifi-registry-autotests-${{ matrix.run-mode }}-logs
          path: |
            ./test-results
          retention-days: 2

